micronaut:
  application:
    name: customers
consul:
  client:
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
db:
  name: 'customers'
  collection: 'customers'
