micronaut:
  application:
    name: customers
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
db:
  name: 'customers'
  collection: 'customers'
