name: CI/CD

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  release:
    types: [ published ]

env:
  REGISTRY: docker.io
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  avoid_redundancy:

    runs-on: ubuntu-latest

    steps:
      - name: cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  coverage_report:

    needs: [ build ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: run coverage report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoTestReport

      - name: upload coverage report
        uses: codecov/codecov-action@v1

  publish:

    if: github.event_name == 'release'

    needs: [ build ]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dockerBuildNative

      - name: push docker image with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dockerPushNative

  deploy:

    if: github.event_name == 'release'

    needs: [ publish ]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - uses: actions/checkout@v3
        with:
          repository: 'https://github.com/dew-org/k8s'

      - name: update deployment file
        run: |-
          sed -i.back "s/customers:0.1.0/customers:${{ github.release.tag_name }}/g" customers/deployment.yml
      - name: deploy
        run: |-
          kubectl apply -f customers/deployment.yml
